### ISSUE TITLE
fstream decode issues

### ISSUE THREAD

**Issue by ealfonsov89** [jimporter/bencode.hpp#4]
I'm getting this error when run the decode with a `fstream`

```bash
terminate called after throwing an instance of 'std::invalid_argument'
  what():  expected string token
```

this is my main code

```c++
#include <fstream>
#include <iostream>
#include <stdio.h>
#include <string>

#include "bencode.hpp"


int main(int argc, char** argv)
{
    std::fstream torrent_file;
    torrent_file.open(argv[1], std::ios_base::in);	
    if (torrent_file.is_open())
    {	
        auto torrent_file_data = bencode::decode(torrent_file);
        torrent_file.close();
    }
    return 0;
}
```

I'm compiling directly in my code using this command `g++  -c  "main.cpp" -g -O0 -std=c++20 -Wall  -o ../build-Debug/main.cpp.o -I. -I.
`

**Comment by jimporter** [comment]
That's an error occurring when you have invalid bencode data. Specifically, when it expects a dict key (which must be a string), but doesn't see a string-start token. What are the contents of the file you're reading?

Maybe the errors could be more informative though...

**Comment by ealfonsov89** [comment]
Hi, I'm reading a .torrent file

```
d8:announce43:udp://tracker.coppersurfer.tk:6969/announce10:created by13:uTorrent/187013:creation datei1462355939e8:encoding5:UTF-84:infod6:lengthi124234e4:name9:puppy.jpg12:piece lengthi16384e6:pieces160:T�k�/�_(�S\u0011h%���+]q\'B\u0018�٠:����p"�j����1-g"\u0018�s(\u001b\u000f���V��=�h�m\u0017a�nF�2���N\r�ǩ�_�\u001e"2���\'�wO���-;\u0004ע\u0017�ؑ��L&����0\u001f�D_9��\t\\��O�h,n\u001a5g�(��仑,�\\߰�%��U��\u0019��C\u0007>��df��ee
```

**Comment by jimporter** [comment]
That's not valid bencode data. The last bit (the value of `info.pieces`) claims to be a 160-byte string, but there are actually 223 characters there. Did the encoding of the file get messed up somehow?

**Comment by jimporter** [comment]
Closing based on the above comment. I've added some improved error reporting here to make diagnosing problems like this easier in 7161e31367707fb12ac0498330ec3b5286eb205d though.
