### ISSUE TITLE
Adding instructions to access decoded values to the readme file for beginners

### ISSUE THREAD

**Issue by nageshky97s** [jimporter/bencode.hpp#6]
Hello,

It would be really wonderful if you added a few comments in the readme file as to how to access decoded values using an with an example like so:

d8:announce55:http://bittorrent-test-tracker.codecrafters.io/announce10:created by13:mktorrent 1.14:**info**d6:lengthi92063e4:name10:sample.txt12:piece lengthi32768e6:pieces60:�v�z*����kg&���-n"u��vfVsn���R��5�
�z����	r'�����ee

How would I access the "info" dictionary from the data object?

It would really helpful for beginners.

**Comment by nageshky97s** [comment]
I'm sorry for opening this issue, accessing values through maps in c++ is not as intuitive as I thought it was. I have figured it out, hence closing the issue.

For people who are trying to figure this out, this is how you access the "length" value in the "info" dictionary (Probably not the best way to do it):

auto data = bencode::decode(buffer); // getting the decoded data

auto value= std::get<bencode::dict>(data); // gets all dictionaries in the current level, can skip this step, added for clarity

//You traverse through the dictionaries to get the data you want, reading up on accessing values from maps in C++ is helpful

auto direct=std::get<bencode::integer>(std::get<bencode::dict>((value.find("info")->second)).find("length")->second);

**Comment by jimporter** [comment]
Yeah, as you noted, it's a fairly verbose process to get the value of some deeply-nested value in your data. That's simply because `std::variant` doesn't provide any easier way to do so. However, I think it would probably be feasible for this library to provide a function like so:

```
auto old = std::get<bencode::integer>(
  std::get<bencode::dict>(
    std::get<bencode::dict>(data)["info"]
  )["length"]
);

auto new = bencode::get<bencode::integer>(data, "info", "length");
```
