### ISSUE TITLE
expected string start token

### ISSUE THREAD

**Issue by xD-saleem** [jimporter/bencode.hpp#8]
hi, i am new to this bencode stuff.

I wanted to use this bencode to parse some torrent bencodes.

I created a small script and included the header.hpp in my project.

int main() {
  std::string input =
      "d8:announce23:udp://tracker.example.com:13374:creation "
      "datei1609459200e4:info"
      "d4:name7:example6:lengthi12345e4:piece40:"
      "0123456789012345678901234567890123456789ee";

  try {
    auto result = bencode::decode(input);
  } catch (const std::exception& e) {
    std::cerr << "Error: " << e.what() << std::endl;
  }

  return 0;
}

However 

i am getting this exception

 Error: expected string start token for dict key, at offset 37
 
 The becode input looks correct. not sure if this is a bug.

**Comment by jimporter** [comment]
Your bencode is malformed. Here's what's going on. The error is in this fragment: `23:udp://tracker.example.com:1337`. This declares a string that's 23 characters long. However, `udp://tracker.example.com:1337` is 30 characters long. So the parser looks at the `o` for the next bencoded element, but that's not a valid start token. (It should be a dict key, so it needs to be a string, and thus the start token needs to be a base-10 number.)

You have some other issues with your data as well though:
* `4:creation date`: You declare a string of length 4, but `creation date` is more than 4 characters.
* `4:piece`: Ditto.

**Comment by xD-saleem** [comment]
yes you are correct sir! I will close this.
